### ISSUE TITLE
Add Qubes to list of platforms with beta notice

### ISSUE THREAD

**Issue by eloquence** [freedomofpress/dangerzone.rocks#27]
Now that Qubes support is in beta, we should add a Qubes OS entry on https://dangerzone.rocks/ with a pointer to the relevant download/installation instructions, and a small notice indicating beta status.

**Comment by apyrgio** [comment]
This issue has been resolved in https://github.com/freedomofpress/dangerzone.rocks/commit/4807de543a9d002bd1ae23d25ed5546f9e41ba28.
